apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: blockscore
  name: blockscore
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: blockscore
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blockscore
    spec:
      containers:
        - name: blockscore
          image: 293637174735.dkr.ecr.us-east-1.amazonaws.com/blockscore:latest
          ports:
            - name: bob
              containerPort: 40334
              protocol: TCP
            - name: ws-port
              containerPort: 8845
              protocol: TCP
            - name: wasm-port
              containerPort: 30344
              protocol: TCP
            - name: wasm-ws-port
              containerPort: 9978
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
         
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
