apiVersion: v1
kind: Service
metadata:
  namespace: freshcredit
  name: blockscore
spec:
  ports:
    - name: bob
      port: 40334
      targetPort: 40334
      protocol: TCP
    - name: ws-port
      port: 8845
      targetPort: 8845
      protocol: TCP
    - name: wasm-port
      port: 30344
      targetPort: 30344
      protocol: TCP
    - name: wasm-ws-port
      port: 9978
      targetPort: 9978
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: blockscore
